
let sample = "AAACACCAACACTCCCGCGTATGTGCAAGAGAAGGCGCTTGGGAGGAAAGGATATCGCCGACGCGTCGGCGCGTCTTCGAAGGACGGCAGATGTAACATATATGCCCACATGAGCGCTCTCGGGAGTGTTATTCACAACCTTTTGCCTTGTGGATACGGGTATACTGGCCTTATTGGCGTACTAGCTGGTCAGTAGGAATACGCGATCATCGTGGACCTGGCCTGGCTACTTGAAGCCGCGGCTTCAGGATTCATAATGGGAATCGAGCTTAATAGGGCTCTCAAGTGAGGACCTTAGTGACCTTGACCCCAATAGCATATAGGGGCTCCCCAGGTCTACAAGATCTGCATGCATATAAGCTGGTCCACGCTGGGGATGGCAGTACATGTAGAGAGCCTATAACTGGGTGGTCTCTATAGATTCACTGGAAAAGATATGACTACTTAATCTTTACCCTTAACTACTTCCAATCCGGCGTCGTCGTTCTGAAAACGTGGAGGTGTTGCTCGTGCCAGCGTCACTTTCTGTCTGTACACCGCCGATACGCAACAAAGCGCTTTGGATTTGTACCGAATCGATCGGCTAGGAGTGGAATCTAGCAAACACATCAATACGTTGGACACATTGCCGCATTACTGTTAACCTGGTGACGGGAAGGGCCACTGGTCTACGCGGTCTTTGGTAGAGGAATGTTGGCCCAAAAATTGGGTTCCCGTTCAGTGCAGCACCGTGCCAGCCCAGTGCATCGAAGACCTTAACAATGCAGCGAGGGCGAGCAGGAGGCAAGCCGCCAAAAGGTAGTTTCAGTATGATCAATCGTTTTTCGGGGATTCTTGGCCTAAGAAAAGAACGTCAAGGGCGGCGTCGCCACA"

sample 
|> Seq.rev
|> Seq.map (function
    | 'A' -> 'T'
    | 'C' -> 'G'
    | 'T' -> 'A'
    | 'G' -> 'C'
    | _ -> failwith "invalid")
|> System.String.Concat 
|> System.Console.WriteLine